name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
         name: Checkout
         uses: actions/checkout@v2
      - 
         name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
      -
         name: docker build
         run: docker build . --file Dockerfile --tag chalut/localtunnel:latest
      -
         name: Docker push
         run: docker push chalut/localtunnel:latest
